export const adjectives = [
  "Jolly",
  "Merry",
  "Festive",
  "Cozy",
  "Sparkling",
  "Twinkling",
  "Gleaming",
  "Glittering",
  "Radiant",
  "Joyful",
  "Cheerful",
  "Frosty",
  "Magical",
  "Enchanting",
  "Whimsical",
  "Lively",
  "Warm",
  "Glistening",
  "Shimmering",
  "Delightful",
  "Luminous",
  "Blissful",
  "Serene",
  "Playful",
  "Exuberant",
  "Vibrant",
  "Dazzling",
  "Sprightly",
  "Resplendent",
  "Jubilant",
  "Gleeful",
  "Angelic",
  "Snug",
  "Enraptured",
  "Cherubic",
  "Mirthful",
  "Bubbly",
  "Sparkly",
  "Lustrous",
  "Ethereal",
  "Piquant",
  "Breathtaking",
  "Ephemeral",
  "Enigmatic",
  "Nebulous",
  "Opulent",
  "Mellifluous",
  "Captivating",
  "Iridescent",
  "Quixotic",
  "Transcendent",
  "Scintillating",
  "Ambrosial",
  "Sanguine",
  "Grandiose",
  "Picturesque",
  "Symbiotic",
  "Zephyr-like",
  "Seraphic",
  "Diaphanous",
  "Symphonic",
  "Vestigial",
  "Effervescent",
  "Incandescent",
  "Ineffable",
];

export const nouns = [
  "Elf",
  "Snowflake",
  "Gingerbread",
  "Mistletoe",
  "Candy Cane",
  "Nutcracker",
  "Sleigh",
  "Tinsel",
  "Stocking",
  "Chimney",
  "North Pole",
  "Wreath",
  "Caroler",
  "Workshop",
  "Snowman",
  "Bauble",
  "Star",
  "Bell",
  "Present",
  "Yule Log",
  "Poinsettia",
  "Icicle",
  "Ornament",
  "Ribbon",
  "Nativity",
  "Fireplace",
  "Jingle Bells",
  "Kringle",
  "Sweets",
  "Comet",
  "Cupid",
  "Donner",
  "Blitzen",
  "Muffler",
  "Tidings",
  "Wonderland",
  "Evergreen",
  "Holly",
  "Sleigh Ride",
  "Candle",
  "Globe",
  "Snow Globe",
  "Cranberry",
  "Fir",
  "Cocoa",
  "Pudding",
  "Silversmith",
  "Fable",
  "Conifer",
  "Wassail",
  "Toboggan",
  "Snuggle",
  "Solstice",
  "Glacier",
  "Epiphany",
  "Polar Bear",
  "Partridge",
  "Snowdrift",
  "Velvet",
  "Aurora",
  "Ginger Snap",
  "Polar Express",
  "Woolen Mittens",
  "Snow Owl",
  "Wintertide",
  "Tundra",
  "Ember",
  "Chestnut",
  "Igloo",
  "Sugar Plum",
  "Cinnamon",
  "Avalanche",
  "Sled",
  "Icy Brook",
  "Candlelight",
  "Marshmallow",
  "Glitter",
  "Bell Choir",
  "Solstice",
  "Sapphire",
  "Ice Sculpture",
  "Frozen Lake",
  "Winter Rose",
  "Everfrost",
  "Turtledove",
  "Crisp Breeze",
  "Blizzard",
  "Snowbound",
  "Starlight",
  "Glowworm",
  "Sugar Frost",
  "Frozen Creek",
  "Twilight",
  "Polar Night",
  "Polar Star",
  "Snowshoe",
  "Frosted Pine",
  "Cranberry Sauce",
];
